In [1]:
import pandas as pd
import numpy as np
from sklearn import ensemble, preprocessing,linear_model, svm

In [2]:
# # increase the number of characters shown for each column
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
train = pd.read_csv("./cleaned_train.csv")
test = pd.read_csv("./cleaned_test.csv")
weather = pd.read_csv("../West-Nile_Team-ATHM/weather_ave_clean.csv")
#sample = pd.read_csv("./sampleSubmission.csv")

In [4]:
from datetime import datetime
train['Date'] = pd.to_datetime(train['Date'], format='%Y-%m-%d')
test['Date'] = pd.to_datetime(test['Date'], format='%Y-%m-%d')
weather['Date'] = pd.to_datetime(weather['Date'], format='%Y-%m-%d')

In [5]:
train['week'] = train['Date'].dt.weekofyear
train['year'] = train['Date'].dt.year
test['week'] = test['Date'].dt.weekofyear
test['year'] = test['Date'].dt.year

In [6]:
train.columns

Index(['Date', 'Address', 'Species', 'Block', 'Street', 'Trap',
       'AddressNumberAndStreet', 'Latitude', 'Longitude', 'AddressAccuracy',
       ...
       'Trap_T903', 'Species_CULEX ERRATICUS', 'Species_CULEX PIPIENS',
       'Species_CULEX PIPIENS/RESTUANS', 'Species_CULEX RESTUANS',
       'Species_CULEX SALINARIUS', 'Species_CULEX TARSALIS',
       'Species_CULEX TERRITANS', 'week', 'year'],
      dtype='object', length=157)

In [7]:
train1 = train.drop(train[['Address',
                           'Block',
                           'Street', 
                           'AddressNumberAndStreet', 
                           'Latitude', 
                           'Longitude',
                           'AddressAccuracy',
                           'Trap_T903', 
                           'Species_CULEX ERRATICUS', 
                           'Species_CULEX PIPIENS',
       'Species_CULEX PIPIENS/RESTUANS', 'Species_CULEX RESTUANS',
       'Species_CULEX SALINARIUS', 'Species_CULEX TARSALIS',
       'Species_CULEX TERRITANS',]], axis=1)

In [8]:
train1.columns

Index(['Date', 'Species', 'Trap', 'NumMosquitos', 'WnvPresent', 'Trap_T001',
       'Trap_T002', 'Trap_T003', 'Trap_T004', 'Trap_T005',
       ...
       'Trap_T231', 'Trap_T232', 'Trap_T233', 'Trap_T235', 'Trap_T236',
       'Trap_T237', 'Trap_T238', 'Trap_T900', 'week', 'year'],
      dtype='object', length=142)

In [9]:
train2 = train1.drop(train[['Trap_T231',
                           'Trap_T232',
                           'Trap_T233', 
                           'Trap_T235', 
                           'Trap_T236',
       'Trap_T237','Trap_T238', 'Trap_T900',
                           'NumMosquitos','Trap_T001',
                           'Trap_T002', 'Trap_T003', 
                           'Trap_T004', 'Trap_T005']], axis=1)

In [10]:
train2.columns

Index(['Date', 'Species', 'Trap', 'WnvPresent', 'Trap_T006', 'Trap_T007',
       'Trap_T008', 'Trap_T009', 'Trap_T011', 'Trap_T012',
       ...
       'Trap_T223', 'Trap_T224', 'Trap_T225', 'Trap_T226', 'Trap_T227',
       'Trap_T228', 'Trap_T229', 'Trap_T230', 'week', 'year'],
      dtype='object', length=128)

In [11]:
train3 = train2.drop(train[['Trap_T223',
                            'Trap_T224',
                            'Trap_T225', 
                            'Trap_T226', 
                            'Trap_T227',
       'Trap_T228', 'Trap_T229', 'Trap_T230','Trap_T006', 'Trap_T007',
       'Trap_T008', 'Trap_T009', 'Trap_T011', 'Trap_T012']], axis=1)

In [12]:
train3.columns

Index(['Date', 'Species', 'Trap', 'WnvPresent', 'Trap_T013', 'Trap_T014',
       'Trap_T015', 'Trap_T016', 'Trap_T017', 'Trap_T018',
       ...
       'Trap_T209', 'Trap_T212', 'Trap_T215', 'Trap_T218', 'Trap_T219',
       'Trap_T220', 'Trap_T221', 'Trap_T222', 'week', 'year'],
      dtype='object', length=114)

In [13]:
train3.head()

,Date,Species,Trap,WnvPresent,Trap_T013,Trap_T014,Trap_T015,Trap_T016,Trap_T017,Trap_T018,Trap_T019,Trap_T025,Trap_T027,Trap_T028,Trap_T030,Trap_T031,Trap_T033,Trap_T034,Trap_T035,Trap_T036,Trap_T037,Trap_T039,Trap_T040,Trap_T043,Trap_T044,Trap_T045,Trap_T046,Trap_T047,Trap_T048,Trap_T049,Trap_T050,Trap_T051,Trap_T054,Trap_T054C,Trap_T060,Trap_T061,Trap_T062,Trap_T063,Trap_T065,Trap_T066,Trap_T067,Trap_T069,Trap_T070,Trap_T071,Trap_T072,Trap_T073,Trap_T074,Trap_T075,Trap_T076,Trap_T077,Trap_T078,Trap_T079,Trap_T080,Trap_T081,Trap_T082,Trap_T083,Trap_T084,Trap_T085,Trap_T086,Trap_T088,Trap_T089,Trap_T090,Trap_T091,Trap_T092,Trap_T094,Trap_T094B,Trap_T095,Trap_T096,Trap_T097,Trap_T099,Trap_T100,Trap_T102,Trap_T103,Trap_T107,Trap_T114,Trap_T115,Trap_T128,Trap_T129,Trap_T135,Trap_T138,Trap_T141,Trap_T142,Trap_T143,Trap_T144,Trap_T145,Trap_T146,Trap_T147,Trap_T148,Trap_T149,Trap_T150,Trap_T151,Trap_T152,Trap_T153,Trap_T154,Trap_T155,Trap_T156,Trap_T157,Trap_T158,Trap_T159,Trap_T160,Trap_T161,Trap_T162,Trap_T200,Trap_T206,Trap_T209,Trap_T212,Trap_T215,Trap_T218,Trap_T219,Trap_T220,Trap_T221,Trap_T222,week,year
0,2007-05-29,CULEX PIPIENS/RESTUANS,T002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,2007
1,2007-05-29,CULEX RESTUANS,T002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,2007
2,2007-05-29,CULEX RESTUANS,T007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,2007
3,2007-05-29,CULEX PIPIENS/RESTUANS,T015,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,2007
4,2007-05-29,CULEX RESTUANS,T015,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,2007

In [14]:
train4 = train3.drop(train[["Trap_T013","Trap_T014","Trap_T015","Trap_T016","Trap_T017","Trap_T018","Trap_T019","Trap_T025","Trap_T027","Trap_T028","Trap_T030","Trap_T031",
"Trap_T033","Trap_T034","Trap_T035","Trap_T036","Trap_T037","Trap_T039","Trap_T040","Trap_T043","Trap_T044","Trap_T045","Trap_T046",
"Trap_T049","Trap_T050","Trap_T051","Trap_T054","Trap_T054C","Trap_T060","Trap_T061","Trap_T062","Trap_T063","Trap_T065",
"Trap_T069","Trap_T070","Trap_T071","Trap_T072","Trap_T073","Trap_T074","Trap_T075","Trap_T076","Trap_T077","Trap_T078","Trap_T079",
"Trap_T080","Trap_T081","Trap_T082","Trap_T083","Trap_T084","Trap_T085","Trap_T086","Trap_T088","Trap_T089","Trap_T090","Trap_T091","Trap_T092",
"Trap_T094","Trap_T094B","Trap_T095","Trap_T096","Trap_T097","Trap_T099","Trap_T100","Trap_T102","Trap_T103","Trap_T107","Trap_T114","Trap_T115",
"Trap_T128","Trap_T129","Trap_T135","Trap_T138","Trap_T141","Trap_T142","Trap_T143","Trap_T144","Trap_T145","Trap_T146","Trap_T147","Trap_T148",
"Trap_T149","Trap_T150","Trap_T151","Trap_T152","Trap_T153","Trap_T154","Trap_T155","Trap_T156","Trap_T157","Trap_T158","Trap_T159","Trap_T160",
"Trap_T161","Trap_T162","Trap_T200","Trap_T206","Trap_T209","Trap_T212","Trap_T215","Trap_T218","Trap_T219","Trap_T220","Trap_T221","Trap_T222"]], axis=1)

In [15]:
train4.columns

Index(['Date', 'Species', 'Trap', 'WnvPresent', 'Trap_T047', 'Trap_T048',
       'Trap_T066', 'Trap_T067', 'week', 'year'],
      dtype='object')

In [16]:
train5 = train4.drop(train[['Trap_T047', 'Trap_T048','Trap_T066','Trap_T067']], axis=1)

In [17]:
train5.head()

        Date                 Species  Trap  WnvPresent  week  year
0 2007-05-29  CULEX PIPIENS/RESTUANS  T002           0    22  2007
1 2007-05-29          CULEX RESTUANS  T002           0    22  2007
2 2007-05-29          CULEX RESTUANS  T007           0    22  2007
3 2007-05-29  CULEX PIPIENS/RESTUANS  T015           0    22  2007
4 2007-05-29          CULEX RESTUANS  T015           0    22  2007

In [18]:
test.columns

Index(['Date', 'Id', 'Address', 'Species', 'Block', 'Street', 'Trap',
       'AddressNumberAndStreet', 'Latitude', 'Longitude',
       ...
       'Species_CULEX ERRATICUS', 'Species_CULEX PIPIENS',
       'Species_CULEX PIPIENS/RESTUANS', 'Species_CULEX RESTUANS',
       'Species_CULEX SALINARIUS', 'Species_CULEX TARSALIS',
       'Species_CULEX TERRITANS', 'Species_UNSPECIFIED CULEX', 'week', 'year'],
      dtype='object', length=170)

In [19]:
test.head().T

,0,1,2,3,4
Date,2008-06-11 00:00:00,2008-06-11 00:00:00,2008-06-11 00:00:00,2008-06-11 00:00:00,2008-06-11 00:00:00
Id,1,2,3,4,5
Address,"4100 North Oak Park Avenue, Chicago, IL 60634, USA","4100 North Oak Park Avenue, Chicago, IL 60634, USA","4100 North Oak Park Avenue, Chicago, IL 60634, USA","4100 North Oak Park Avenue, Chicago, IL 60634, USA","4100 North Oak Park Avenue, Chicago, IL 60634, USA"
Species,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX PIPIENS,CULEX SALINARIUS,CULEX TERRITANS
Block,41,41,41,41,41
Street,N OAK PARK AVE,N OAK PARK AVE,N OAK PARK AVE,N OAK PARK AVE,N OAK PARK AVE
Trap,T002,T002,T002,T002,T002
AddressNumberAndStreet,"4100 N OAK PARK AVE, Chicago, IL","4100 N OAK PARK AVE, Chicago, IL","4100 N OAK PARK AVE, Chicago, IL","4100 N OAK PARK AVE, Chicago, IL","4100 N OAK PARK AVE, Chicago, IL"
Latitude,41.9547,41.9547,41.9547,41.9547,41.9547
Longitude,-87.801,-87.801,-87.801,-87.801,-87.801
AddressAccuracy,9,9,9,9,9
Trap_T001,0,0,0,0,0
Trap_T002,1,1,1,1,1
Trap_T002A,0,0,0,0,0
Trap_T002B,0,0,0,0,0
Trap_T003,0,0,0,0,0
Trap_T004,0,0,0,0,0
Trap_T005,0,0,0,0,0
Trap_T006,0,0,0,0,0
Trap_T007,0,0,0,0,0
Trap_T008,0,0,0,0,0
Trap_T009,0,0,0,0,0
Trap_T011,0,0,0,0,0
Trap_T012,0,0,0,0,0
Trap_T013,0,0,0,0,0
Trap_T014,0,0,0,0,0
Trap_T015,0,0,0,0,0
Trap_T016,0,0,0,0,0
Trap_T017,0,0,0,0,0
Trap_T018,0,0,0,0,0
Trap_T019,0,0,0,0,0
Trap_T025,0,0,0,0,0
Trap_T027,0,0,0,0,0
Trap_T028,0,0,0,0,0
Trap_T030,0,0,0,0,0
Trap_T031,0,0,0,0,0
Trap_T033,0,0,0,0,0
Trap_T034,0,0,0,0,0
Trap_T035,0,0,0,0,0
Trap_T036,0,0,0,0,0
Trap_T037,0,0,0,0,0
Trap_T039,0,0,0,0,0
Trap_T040,0,0,0,0,0
Trap_T043,0,0,0,0,0
Trap_T044,0,0,0,0,0
Trap_T045,0,0,0,0,0
Trap_T046,0,0,0,0,0
Trap_T047,0,0,0,0,0
Trap_T048,0,0,0,0,0
Trap_T049,0,0,0,0,0
Trap_T050,0,0,0,0,0
Trap_T051,0,0,0,0,0
Trap_T054,0,0,0,0,0
Trap_T054C,0,0,0,0,0
Trap_T060,0,0,0,0,0
Trap_T061,0,0,0,0,0
Trap_T062,0,0,0,0,0
Trap_T063,0,0,0,0,0
Trap_T065,0,0,0,0,0
Trap_T065A,0,0,0,0,0
Trap_T066,0,0,0,0,0
Trap_T067,0,0,0,0,0
Trap_T069,0,0,0,0,0
Trap_T070,0,0,0,0,0
Trap_T071,0,0,0,0,0
Trap_T072,0,0,0,0,0
Trap_T073,0,0,0,0,0
Trap_T074,0,0,0,0,0
Trap_T075,0,0,0,0,0
Trap_T076,0,0,0,0,0
Trap_T077,0,0,0,0,0
Trap_T078,0,0,0,0,0
Trap_T079,0,0,0,0,0
Trap_T080,0,0,0,0,0
Trap_T081,0,0,0,0,0
Trap_T082,0,0,0,0,0
Trap_T083,0,0,0,0,0
Trap_T084,0,0,0,0,0
Trap_T085,0,0,0,0,0
Trap_T086,0,0,0,0,0
Trap_T088,0,0,0,0,0
Trap_T089,0,0,0,0,0
Trap_T090,0,0,0,0,0
Trap_T090A,0,0,0,0,0
Trap_T090B,0,0,0,0,0
Trap_T090C,0,0,0,0,0
Trap_T091,0,0,0,0,0
Trap_T092,0,0,0,0,0
Trap_T094,0,0,0,0,0
Trap_T094B,0,0,0,0,0
Trap_T095,0,0,0,0,0
Trap_T096,0,0,0,0,0
Trap_T097,0,0,0,0,0
Trap_T099,0,0,0,0,0
Trap_T100,0,0,0,0,0
Trap_T102,0,0,0,0,0
Trap_T103,0,0,0,0,0
Trap_T107,0,0,0,0,0
Trap_T114,0,0,0,0,0
Trap_T115,0,0,0,0,0
Trap_T128,0,0,0,0,0
Trap_T128A,0,0,0,0,0
Trap_T129,0,0,0,0,0
Trap_T135,0,0,0,0,0
Trap_T138,0,0,0,0,0
Trap_T141,0,0,0,0,0
Trap_T142,0,0,0,0,0
Trap_T143,0,0,0,0,0
Trap_T144,0,0,0,0,0
Trap_T145,0,0,0,0,0
Trap_T146,0,0,0,0,0
Trap_T147,0,0,0,0,0
Trap_T148,0,0,0,0,0
Trap_T149,0,0,0,0,0
Trap_T150,0,0,0,0,0
Trap_T151,0,0,0,0,0
Trap_T152,0,0,0,0,0
Trap_T153,0,0,0,0,0
Trap_T154,0,0,0,0,0
Trap_T155,0,0,0,0,0
Trap_T156,0,0,0,0,0
Trap_T157,0,0,0,0,0
Trap_T158,0,0,0,0,0
Trap_T159,0,0,0,0,0
Trap_T160,0,0,0,0,0
Trap_T161,0,0,0,0,0
Trap_T162,0,0,0,0,0
Trap_T200,0,0,0,0,0
Trap_T200A,0,0,0,0,0
Trap_T200B,0,0,0,0,0
Trap_T206,0,0,0,0,0
Trap_T209,0,0,0,0,0
Trap_T212,0,0,0,0,0
Trap_T215,0,0,0,0,0
Trap_T218,0,0,0,0,0
Trap_T218A,0,0,0,0,0
Trap_T218B,0,0,0,0,0
Trap_T218C,0,0,0,0,0
Trap_T219,0,0,0,0,0
Trap_T220,0,0,0,0,0
Trap_T221,0,0,0,0,0
Trap_T222,0,0,0,0,0
Trap_T223,0,0,0,0,0
Trap_T224,0,0,0,0,0
Trap_T225,0,0,0,0,0
Trap_T226,0,0,0,0,0
Trap_T227,0,0,0,0,0
Trap_T228,0,0,0,0,0
Trap_T229,0,0,0,0,0
Trap_T230,0,0,0,0,0
Trap_T231,0,0,0,0,0
Trap_T232,0,0,0,0,0
Trap_T233,0,0,0,0,0
Trap_T234,0,0,0,0,0
Trap_T235,0,0,0,0,0
Trap_T236,0,0,0,0,0
Trap_T237,0,0,0,0,0
Trap_T238,0,0,0,0,0
Trap_T900,0,0,0,0,0
Trap_T903,0,0,0,0,0
Species_CULEX ERRATICUS,0,0,0,0,0
Species_CULEX PIPIENS,0,0,1,0,0
Species_CULEX PIPIENS/RESTUANS,1,0,0,0,0
Species_CULEX RESTUANS,0,1,0,0,0
Species_CULEX SALINARIUS,0,0,0,1,0
Species_CULEX TARSALIS,0,0,0,0,0
Species_CULEX TERRITANS,0,0,0,0,1
Species_UNSPECIFIED CULEX,0,0,0,0,0
week,24,24,24,24,24
year,2008,2008,2008,2008,2008

In [20]:
test1 = test.drop(test[["Trap_T013","Trap_T014","Trap_T015","Trap_T016","Trap_T017","Trap_T018","Trap_T019","Trap_T025","Trap_T027","Trap_T028","Trap_T030","Trap_T031",
"Trap_T033","Trap_T034","Trap_T035","Trap_T036","Trap_T037","Trap_T039","Trap_T040","Trap_T043","Trap_T044","Trap_T045","Trap_T046",
"Trap_T049","Trap_T050","Trap_T051","Trap_T054","Trap_T054C","Trap_T060","Trap_T061","Trap_T062","Trap_T063","Trap_T065",
"Trap_T069","Trap_T070","Trap_T071","Trap_T072","Trap_T073","Trap_T074","Trap_T075","Trap_T076","Trap_T077","Trap_T078","Trap_T079",
"Trap_T080","Trap_T081","Trap_T082","Trap_T083","Trap_T084","Trap_T085","Trap_T086","Trap_T088","Trap_T089","Trap_T090","Trap_T091","Trap_T092",
"Trap_T094","Trap_T094B","Trap_T095","Trap_T096","Trap_T097","Trap_T099","Trap_T100","Trap_T102","Trap_T103","Trap_T107","Trap_T114","Trap_T115",
"Trap_T128","Trap_T129","Trap_T135","Trap_T138","Trap_T141","Trap_T142","Trap_T143","Trap_T144","Trap_T145","Trap_T146","Trap_T147","Trap_T148",
"Trap_T149","Trap_T150","Trap_T151","Trap_T152","Trap_T153","Trap_T154","Trap_T155","Trap_T156","Trap_T157","Trap_T158","Trap_T159","Trap_T160",
"Trap_T161","Trap_T162","Trap_T200","Trap_T206","Trap_T209","Trap_T212","Trap_T215","Trap_T218","Trap_T219","Trap_T220","Trap_T221","Trap_T222"]], axis=1)

In [21]:
test1.columns

Index(['Date', 'Id', 'Address', 'Species', 'Block', 'Street', 'Trap',
       'AddressNumberAndStreet', 'Latitude', 'Longitude', 'AddressAccuracy',
       'Trap_T001', 'Trap_T002', 'Trap_T002A', 'Trap_T002B', 'Trap_T003',
       'Trap_T004', 'Trap_T005', 'Trap_T006', 'Trap_T007', 'Trap_T008',
       'Trap_T009', 'Trap_T011', 'Trap_T012', 'Trap_T047', 'Trap_T048',
       'Trap_T065A', 'Trap_T066', 'Trap_T067', 'Trap_T090A', 'Trap_T090B',
       'Trap_T090C', 'Trap_T128A', 'Trap_T200A', 'Trap_T200B', 'Trap_T218A',
       'Trap_T218B', 'Trap_T218C', 'Trap_T223', 'Trap_T224', 'Trap_T225',
       'Trap_T226', 'Trap_T227', 'Trap_T228', 'Trap_T229', 'Trap_T230',
       'Trap_T231', 'Trap_T232', 'Trap_T233', 'Trap_T234', 'Trap_T235',
       'Trap_T236', 'Trap_T237', 'Trap_T238', 'Trap_T900', 'Trap_T903',
       'Species_CULEX ERRATICUS', 'Species_CULEX PIPIENS',
       'Species_CULEX PIPIENS/RESTUANS', 'Species_CULEX RESTUANS',
       'Species_CULEX SALINARIUS', 'Species_CULEX TARSALIS',
       'Species_CULEX TERRITANS', 'Species_UNSPECIFIED CULEX', 'week', 'year'],
      dtype='object')

In [22]:
test2 = test1.drop(test[[ 'AddressNumberAndStreet', 'Latitude', 'Longitude', 'AddressAccuracy',
       'Trap_T001', 'Trap_T002', 'Trap_T002A', 'Trap_T002B', 'Trap_T003',
       'Trap_T004', 'Trap_T005', 'Trap_T006', 'Trap_T007', 'Trap_T008',
       'Trap_T009', 'Trap_T011', 'Trap_T012', 'Trap_T047', 'Trap_T048',
       'Trap_T065A', 'Trap_T066', 'Trap_T067', 'Trap_T090A', 'Trap_T090B',
       'Trap_T090C', 'Trap_T128A', 'Trap_T200A', 'Trap_T200B', 'Trap_T218A',
       'Trap_T218B', 'Trap_T218C', 'Trap_T223', 'Trap_T224', 'Trap_T225',
       'Trap_T226', 'Trap_T227', 'Trap_T228', 'Trap_T229', 'Trap_T230',
       'Trap_T231', 'Trap_T232', 'Trap_T233', 'Trap_T234', 'Trap_T235',
       'Trap_T236', 'Trap_T237', 'Trap_T238', 'Trap_T900', 'Trap_T903',
       'Species_CULEX ERRATICUS', 'Species_CULEX PIPIENS',
       'Species_CULEX PIPIENS/RESTUANS', 'Species_CULEX RESTUANS',
       'Species_CULEX SALINARIUS', 'Species_CULEX TARSALIS',
       'Species_CULEX TERRITANS', 'Species_UNSPECIFIED CULEX',]], axis=1)

In [23]:
test2.columns

Index(['Date', 'Id', 'Address', 'Species', 'Block', 'Street', 'Trap', 'week',
       'year'],
      dtype='object')

In [24]:
test3 = test2.drop(test[['Id','Address','Block', 'Street',]], axis=1)

In [25]:
test3.head()

        Date                 Species  Trap  week  year
0 2008-06-11  CULEX PIPIENS/RESTUANS  T002    24  2008
1 2008-06-11          CULEX RESTUANS  T002    24  2008
2 2008-06-11           CULEX PIPIENS  T002    24  2008
3 2008-06-11        CULEX SALINARIUS  T002    24  2008
4 2008-06-11         CULEX TERRITANS  T002    24  2008

In [26]:
weather.head()

,Station,Date,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,HZ,VC,FU,BC,SQ,FG+,MI,TS,DZ,RA,BR,FG,SN
0,1,2007-05-01,83.0,50.0,67.0,14.0,51.0,56.000000,0.0,2.0,0.0,29.100,29.8200,1.7,27,9.200000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,2,2007-05-01,84.0,50.0,67.5,29.5,51.0,56.500000,0.0,2.0,0.0,29.140,29.8200,2.7,25,9.400000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
2,1,2007-05-02,84.0,42.0,62.0,-3.0,48.0,53.333333,14.0,0.0,0.0,29.220,29.9100,13.0,4,10.733333,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.333333,0.0,0.0
3,2,2007-05-02,84.0,42.0,59.5,29.5,46.5,51.750000,14.0,0.0,0.0,29.275,29.9525,13.3,2,11.400000,0.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.500000,0.0,0.0
4,1,2007-05-03,84.0,42.0,58.8,2.0,45.2,51.000000,14.0,0.0,0.0,29.298,29.9860,13.3,7,11.500000,0.20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.400000,0.0,0.0

In [27]:
weather['Date'] = pd.to_datetime(weather['Date'], format='%Y-%m-%d')

In [28]:
# Adding the weather data to the train and test data
train_add =train5.join(weather.set_index('Date'), on='Date')
test_add = test3.join(weather.set_index('Date'), on='Date')

In [29]:
train_add.head()

,Date,Species,Trap,WnvPresent,week,year,Station,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,HZ,VC,FU,BC,SQ,FG+,MI,TS,DZ,RA,BR,FG,SN
0,2007-05-29,CULEX PIPIENS/RESTUANS,T002,0,22,2007,1,90.0,42.0,64.800000,10.0,45.600000,54.533333,12.0,0.0,0.096333,29.411667,30.098667,14.9,18,10.046667,0.133333,0.033333,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.466667,0.333333,0.0,0.0
0,2007-05-29,CULEX PIPIENS/RESTUANS,T002,0,22,2007,2,89.0,42.0,64.966667,29.5,46.066667,54.800000,12.0,0.0,0.096333,29.416000,30.102333,14.9,16,9.806667,0.166667,0.033333,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.466667,0.366667,0.0,0.0
1,2007-05-29,CULEX RESTUANS,T002,0,22,2007,1,90.0,42.0,64.800000,10.0,45.600000,54.533333,12.0,0.0,0.096333,29.411667,30.098667,14.9,18,10.046667,0.133333,0.033333,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.466667,0.333333,0.0,0.0
1,2007-05-29,CULEX RESTUANS,T002,0,22,2007,2,89.0,42.0,64.966667,29.5,46.066667,54.800000,12.0,0.0,0.096333,29.416000,30.102333,14.9,16,9.806667,0.166667,0.033333,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.466667,0.366667,0.0,0.0
2,2007-05-29,CULEX RESTUANS,T007,0,22,2007,1,90.0,42.0,64.800000,10.0,45.600000,54.533333,12.0,0.0,0.096333,29.411667,30.098667,14.9,18,10.046667,0.133333,0.033333,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.466667,0.333333,0.0,0.0

In [30]:
test_add.head()

,Date,Species,Trap,week,year,Station,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,HZ,VC,FU,BC,SQ,FG+,MI,TS,DZ,RA,BR,FG,SN
0,2008-06-11,CULEX PIPIENS/RESTUANS,T002,24,2008,1,88.0,42.0,68.2,7.0,56.300000,61.366667,16.0,0.0,0.207667,29.189333,29.872667,21.1,18,9.990000,0.1,0.0,0.0,0.0,0.033333,0.066667,0.0,0.333333,0.066667,0.700000,0.366667,0.066667,0.0
0,2008-06-11,CULEX PIPIENS/RESTUANS,T002,24,2008,2,88.0,42.0,69.1,29.5,56.933333,62.066667,12.0,0.0,0.207667,29.182667,29.865667,21.1,18,9.756667,0.1,0.0,0.0,0.0,0.033333,0.066667,0.0,0.333333,0.066667,0.666667,0.366667,0.066667,0.0
1,2008-06-11,CULEX RESTUANS,T002,24,2008,1,88.0,42.0,68.2,7.0,56.300000,61.366667,16.0,0.0,0.207667,29.189333,29.872667,21.1,18,9.990000,0.1,0.0,0.0,0.0,0.033333,0.066667,0.0,0.333333,0.066667,0.700000,0.366667,0.066667,0.0
1,2008-06-11,CULEX RESTUANS,T002,24,2008,2,88.0,42.0,69.1,29.5,56.933333,62.066667,12.0,0.0,0.207667,29.182667,29.865667,21.1,18,9.756667,0.1,0.0,0.0,0.0,0.033333,0.066667,0.0,0.333333,0.066667,0.666667,0.366667,0.066667,0.0
2,2008-06-11,CULEX PIPIENS,T002,24,2008,1,88.0,42.0,68.2,7.0,56.300000,61.366667,16.0,0.0,0.207667,29.189333,29.872667,21.1,18,9.990000,0.1,0.0,0.0,0.0,0.033333,0.066667,0.0,0.333333,0.066667,0.700000,0.366667,0.066667,0.0

In [31]:
#get dummies for species
train_add = pd.concat([train_add , pd.get_dummies(train_add['Species'])], axis=1) 
test_add = pd.concat([test_add , pd.get_dummies(test_add['Species'])], axis=1)  
train_add['UNSPECIFIED CULEX']= 0

In [32]:
#get dummies for Traps
train_add = pd.concat([train_add , pd.get_dummies(train_add['Trap'])], axis=1) 
test_add = pd.concat([test_add , pd.get_dummies(test_add['Trap'])], axis=1)

In [33]:
train_add['T090A']= train_add['T090']
train_add['T090B']= train_add['T090']
train_add['T090C']= train_add['T090']
train_add['T002A']= train_add['T002']
train_add['T002B']= train_add['T002']
train_add['T218A']= train_add['T218']
train_add['T218B']= train_add['T218']
train_add['T218C']= train_add['T218']
train_add['T128A']= train_add['T128']
train_add['T200A']= train_add['T200']
train_add['T200B']= train_add['T200']
train_add['T065A']= train_add['T065']
train_add['T234']= train_add['T141'] # closest trap

In [34]:
train_add.head(2)

,Date,Species,Trap,WnvPresent,week,year,Station,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,HZ,VC,FU,BC,SQ,FG+,MI,TS,DZ,RA,BR,FG,SN,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX,T001,T002,T003,T004,T005,T006,T007,T008,T009,T011,T012,T013,T014,T015,T016,T017,T018,T019,T025,T027,T028,T030,T031,T033,T034,T035,T036,T037,T039,T040,T043,T044,T045,T046,T047,T048,T049,T050,T051,T054,T054C,T060,T061,T062,T063,T065,T066,T067,T069,T070,T071,T072,T073,T074,T075,T076,T077,T078,T079,T080,T081,T082,T083,T084,T085,T086,T088,T089,T090,T091,T092,T094,T094B,T095,T096,T097,T099,T100,T102,T103,T107,T114,T115,T128,T129,T135,T138,T141,T142,T143,T144,T145,T146,T147,T148,T149,T150,T151,T152,T153,T154,T155,T156,T157,T158,T159,T160,T161,T162,T200,T206,T209,T212,T215,T218,T219,T220,T221,T222,T223,T224,T225,T226,T227,T228,T229,T230,T231,T232,T233,T235,T236,T237,T238,T900,T903,T090A,T090B,T090C,T002A,T002B,T218A,T218B,T218C,T128A,T200A,T200B,T065A,T234
0,2007-05-29,CULEX PIPIENS/RESTUANS,T002,0,22,2007,1,90.0,42.0,64.800000,10.0,45.600000,54.533333,12.0,0.0,0.096333,29.411667,30.098667,14.9,18,10.046667,0.133333,0.033333,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.466667,0.333333,0.0,0.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
0,2007-05-29,CULEX PIPIENS/RESTUANS,T002,0,22,2007,2,89.0,42.0,64.966667,29.5,46.066667,54.800000,12.0,0.0,0.096333,29.416000,30.102333,14.9,16,9.806667,0.166667,0.033333,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.466667,0.366667,0.0,0.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0

In [35]:
test_add.head(2)

,Date,Species,Trap,week,year,Station,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,HZ,VC,FU,BC,SQ,FG+,MI,TS,DZ,RA,BR,FG,SN,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX,T001,T002,T002A,T002B,T003,T004,T005,T006,T007,T008,T009,T011,T012,T013,T014,T015,T016,T017,T018,T019,T025,T027,T028,T030,T031,T033,T034,T035,T036,T037,T039,T040,T043,T044,T045,T046,T047,T048,T049,T050,T051,T054,T054C,T060,T061,T062,T063,T065,T065A,T066,T067,T069,T070,T071,T072,T073,T074,T075,T076,T077,T078,T079,T080,T081,T082,T083,T084,T085,T086,T088,T089,T090,T090A,T090B,T090C,T091,T092,T094,T094B,T095,T096,T097,T099,T100,T102,T103,T107,T114,T115,T128,T128A,T129,T135,T138,T141,T142,T143,T144,T145,T146,T147,T148,T149,T150,T151,T152,T153,T154,T155,T156,T157,T158,T159,T160,T161,T162,T200,T200A,T200B,T206,T209,T212,T215,T218,T218A,T218B,T218C,T219,T220,T221,T222,T223,T224,T225,T226,T227,T228,T229,T230,T231,T232,T233,T234,T235,T236,T237,T238,T900,T903
0,2008-06-11,CULEX PIPIENS/RESTUANS,T002,24,2008,1,88.0,42.0,68.2,7.0,56.300000,61.366667,16.0,0.0,0.207667,29.189333,29.872667,21.1,18,9.990000,0.1,0.0,0.0,0.0,0.033333,0.066667,0.0,0.333333,0.066667,0.700000,0.366667,0.066667,0.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,2008-06-11,CULEX PIPIENS/RESTUANS,T002,24,2008,2,88.0,42.0,69.1,29.5,56.933333,62.066667,12.0,0.0,0.207667,29.182667,29.865667,21.1,18,9.756667,0.1,0.0,0.0,0.0,0.033333,0.066667,0.0,0.333333,0.066667,0.666667,0.366667,0.066667,0.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [36]:
test_add= test_add.drop('Date', axis=1)
train_add= train_add.drop('Date', axis=1)
test_add= test_add.drop('Species', axis=1)
train_add= train_add.drop('Species', axis=1)
test_add= test_add.drop('Trap', axis=1)
train_add= train_add.drop('Trap', axis=1)

In [37]:
train_add.head(2)

,WnvPresent,week,year,Station,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,HZ,VC,FU,BC,SQ,FG+,MI,TS,DZ,RA,BR,FG,SN,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX,T001,T002,T003,T004,T005,T006,T007,T008,T009,T011,T012,T013,T014,T015,T016,T017,T018,T019,T025,T027,T028,T030,T031,T033,T034,T035,T036,T037,T039,T040,T043,T044,T045,T046,T047,T048,T049,T050,T051,T054,T054C,T060,T061,T062,T063,T065,T066,T067,T069,T070,T071,T072,T073,T074,T075,T076,T077,T078,T079,T080,T081,T082,T083,T084,T085,T086,T088,T089,T090,T091,T092,T094,T094B,T095,T096,T097,T099,T100,T102,T103,T107,T114,T115,T128,T129,T135,T138,T141,T142,T143,T144,T145,T146,T147,T148,T149,T150,T151,T152,T153,T154,T155,T156,T157,T158,T159,T160,T161,T162,T200,T206,T209,T212,T215,T218,T219,T220,T221,T222,T223,T224,T225,T226,T227,T228,T229,T230,T231,T232,T233,T235,T236,T237,T238,T900,T903,T090A,T090B,T090C,T002A,T002B,T218A,T218B,T218C,T128A,T200A,T200B,T065A,T234
0,0,22,2007,1,90.0,42.0,64.800000,10.0,45.600000,54.533333,12.0,0.0,0.096333,29.411667,30.098667,14.9,18,10.046667,0.133333,0.033333,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.466667,0.333333,0.0,0.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
0,0,22,2007,2,89.0,42.0,64.966667,29.5,46.066667,54.800000,12.0,0.0,0.096333,29.416000,30.102333,14.9,16,9.806667,0.166667,0.033333,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.466667,0.366667,0.0,0.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0

In [38]:
test_add.head(2)

,week,year,Station,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed,HZ,VC,FU,BC,SQ,FG+,MI,TS,DZ,RA,BR,FG,SN,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,UNSPECIFIED CULEX,T001,T002,T002A,T002B,T003,T004,T005,T006,T007,T008,T009,T011,T012,T013,T014,T015,T016,T017,T018,T019,T025,T027,T028,T030,T031,T033,T034,T035,T036,T037,T039,T040,T043,T044,T045,T046,T047,T048,T049,T050,T051,T054,T054C,T060,T061,T062,T063,T065,T065A,T066,T067,T069,T070,T071,T072,T073,T074,T075,T076,T077,T078,T079,T080,T081,T082,T083,T084,T085,T086,T088,T089,T090,T090A,T090B,T090C,T091,T092,T094,T094B,T095,T096,T097,T099,T100,T102,T103,T107,T114,T115,T128,T128A,T129,T135,T138,T141,T142,T143,T144,T145,T146,T147,T148,T149,T150,T151,T152,T153,T154,T155,T156,T157,T158,T159,T160,T161,T162,T200,T200A,T200B,T206,T209,T212,T215,T218,T218A,T218B,T218C,T219,T220,T221,T222,T223,T224,T225,T226,T227,T228,T229,T230,T231,T232,T233,T234,T235,T236,T237,T238,T900,T903
0,24,2008,1,88.0,42.0,68.2,7.0,56.300000,61.366667,16.0,0.0,0.207667,29.189333,29.872667,21.1,18,9.990000,0.1,0.0,0.0,0.0,0.033333,0.066667,0.0,0.333333,0.066667,0.700000,0.366667,0.066667,0.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,24,2008,2,88.0,42.0,69.1,29.5,56.933333,62.066667,12.0,0.0,0.207667,29.182667,29.865667,21.1,18,9.756667,0.1,0.0,0.0,0.0,0.033333,0.066667,0.0,0.333333,0.066667,0.666667,0.366667,0.066667,0.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [39]:
print (test_add.shape)
print (train_add.shape)

(232586, 187)
(21012, 188)

In [40]:
train_add.to_csv('train_merged_weather.csv',index_label=False)

In [41]:
test_add.to_csv('test_merged_weather.csv',index_label=False)

In [42]:
y =train_add['WnvPresent']

In [43]:
train_add = train_add.drop('WnvPresent', axis=1)

In [44]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report,roc_auc_score
from sklearn.cross_validation import cross_val_score, StratifiedKFold ,train_test_split, KFold
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, BaggingClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import GridSearchCV

/Users/Hakob/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [45]:
train_add.columns

Index(['week', 'year', 'Station', 'Tmax', 'Tmin', 'Tavg', 'Depart', 'DewPoint',
       'WetBulb', 'Heat',
       ...
       'T002A', 'T002B', 'T218A', 'T218B', 'T218C', 'T128A', 'T200A', 'T200B',
       'T065A', 'T234'],
      dtype='object', length=187)

In [46]:
X =train_add

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [48]:
##Grid search over Random Forest parameters
# model evaluation and prediction function
def evaluate_model(model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    a = accuracy_score(y_test, y_pred)
    probabilities = model.predict_proba(X_test)
    #cm = confusion_matrix(y_test, y_pred)
    conmat = np.array(confusion_matrix(y_test, y_pred, labels=[1,0]))

    confusion = pd.DataFrame(conmat, index=['1', '0'],
                         columns=['predicted_1','predicted_0'])

    cr = classification_report(y_test, y_pred)
    
    print ('confusion matrix:')
    print (confusion)
    print ('classification_report:')
    print (cr)
    print ('Accuracy of the model on test:',a)
    return probabilities
#params = {'max_features ': [0.5,1.0],'max_depth':[0.5,1.0],'n_estimators':[5,10]}
max_depths = [0.3, 0.5,1.0]
max_features = [0.3,0.5,1.0]
n_estimators = [5000]

rf = RandomForestClassifier(n_jobs=-1,random_state = 33, class_weight='balanced')
gsrf = GridSearchCV(estimator = rf,param_grid=dict(max_depth = max_depths, max_features=max_features,n_estimators=n_estimators), n_jobs=-1,cv=3,scoring='roc_auc')
gsrf.fit(X_train, y_train)
print ('best parameters for the model:',gsrf.best_params_)
print ('best score on train:',gsrf.best_score_)
probability = evaluate_model(gsrf.best_estimator_)

best parameters for the model: {'max_depth': 1.0, 'max_features': 0.3, 'n_estimators': 5000}
best score on train: 0.7814016374391666
confusion matrix:
   predicted_1  predicted_0
1          261          106
0         1882         4685
classification_report:
             precision    recall  f1-score   support

          0       0.98      0.71      0.82      6567
          1       0.12      0.71      0.21       367

avg / total       0.93      0.71      0.79      6934

Accuracy of the model on test: 0.7132967983847707

In [49]:
##Grid search over Logestic Regression parameters
# model evaluation function
def evaluate_model(model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
   
    a = accuracy_score(y_test, y_pred)
    probabilities = model.predict_proba(X_test)
#cm = confusion_matrix(y_test, y_pred)
    conmat = np.array(confusion_matrix(y_test, y_pred, labels=[1,0]))

    confusion = pd.DataFrame(conmat, index=['1', '0'],
                        columns=['predicted_1','predicted_0'])

    cr = classification_report(y_test, y_pred)
   
    print ('confusion matrix:')
    print (confusion)
    print ('classification_report:')
    print (cr)
    print ('Accuracy of the model on test:',a)
    return probabilities

penalty =  ['l2','l1']
C = [0.1,1.0,10]
lg = LogisticRegression()
gslg = GridSearchCV(estimator = lg,param_grid=dict(C=C, penalty=penalty), n_jobs=-1,cv=3,scoring='roc_auc')
gslg.fit(X_train, y_train)
print ('best parameters for the model:',gslg.best_params_)
print ('best score on train:',gslg.best_score_)
probability = evaluate_model(gslg.best_estimator_)

best parameters for the model: {'C': 10, 'penalty': 'l1'}
best score on train: 0.8354069192599471
confusion matrix:
   predicted_1  predicted_0
1            9          358
0            4         6563
classification_report:
             precision    recall  f1-score   support

          0       0.95      1.00      0.97      6567
          1       0.69      0.02      0.05       367

avg / total       0.93      0.95      0.92      6934

Accuracy of the model on test: 0.9477934813960196

In [50]:
from sklearn.model_selection import cross_val_score
def evaluate_model(model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    a = accuracy_score(y_test, y_pred)
    probabilities = model.predict_proba(X_test)
    #cm = confusion_matrix(y_test, y_pred)
    conmat = np.array(confusion_matrix(y_test, y_pred, labels=[1,0]))

    confusion = pd.DataFrame(conmat, index=['1', '0'],
                         columns=['predicted_1','predicted_0'])

    cr = classification_report(y_test, y_pred)
    
    print ('confusion matrix:')
    print( confusion)
    print ('classification_report:')
    print (cr)
    print ('Accuracy of the model on test:',a)
    return probabilities
gbc = GradientBoostingClassifier(random_state = 33,max_depth = 1.0,max_features = 0.3,n_estimators = 5000)
gbc.fit(X_train, y_train)
scores = cross_val_score(gbc, X_train, y_train, cv=5, scoring='roc_auc')

In [51]:
pro_gbc2 = gbc.predict_proba(test_add)

In [52]:
scores.mean()

0.8557722271482913